### PR TITLE
Make cursor visitor abide to the cgo pointer passing rules

### PR DESCRIPTION
**Pull request by doppioandante**
I have never used cgo before, this is what I could put up reading a bit here and there. Please review.

### CODE REVIEW

**Comment by sbinet** [comment]
thanks. LGTM.

(please note that I (and others) have refactored `github.com/sbinet/go-clang` inside `github.com/go-clang` with a much better clang multi-version support)

could you please reword your commit message to be more like the others?
_e.g.:_

```
cursor: follow go-1.6 cgo pointer rules

Fixes #17
```

thanks again.

**Comment by doppioandante** [comment]
Damn I could have spared the effort: https://github.com/go-clang/bootstrap/pull/10

That PR deals with a (very unlikely) case that mine doesn't consider, but I'm puzzled buy the int type, supposing that the author's intent is to make the map reusable in case of counter overflow.

Is there any particular difference between this repo and the generated ones? If not, I would add a note on top of the README telling that this one has moved (it still has the most starts on github, this is why I had choosen it)

**Comment by zimmski** [comment]
@doppioandante I look at this the same way as sbinet does. Your PR is needed.
We did not mark the go-clang repositories as "ready" so sbinet's go-clang repository is still first choice if you do not want to deal with new problems. But if you have the time, it would be greatly appreciated if you could test your programs with the new go-clang repositories.

**Comment by doppioandante** [comment]
@zimmski  I see, I will try the new repositories for sure. About this PR, can you explain me the logic behind your pull request (go-clang/bootstrap#10) that fixes this same problem? It is slightly different from mine.
@sbinet I'm sorry for not modyfing the message, I didn't think it would have been merged so fast.

**Comment by sbinet** [comment]
@doppioandante no worries (it was a finger problem on my side: I applied the `README.md` fixes on top of `master` which had been rebased on top of your branch. all my bad :))

**Comment by zimmski** [comment]
@doppioandante:
- You are using uintptr as the index I am using int. I am then using a pointer to forward the value to the C calls, you are forwarding the uintptr value. I do not know if this might lead to a problem. The type should not matter, I am talking about using a real pointer vs the value of the type uintptr.
- The `index++` can lead to an overflow. It could be, that an index is chosen that is still in use. That is the purpose of the for loop.
  Besides that I do not see any big differences.

**Comment by doppioandante** [comment]
@zimmski 
- I actually modified _go_clang_visit_children to accept the index instead of the pointer, we gain a little bit of type safety even though there must be a cast eventually.
- The overflow can (even though rarely?) happen, I will add the for loop as well, I was puzzled by the fact that the index will become negative with an int, but it isn't a problem with a map.

Also I'm not sure about the lookup function anymore, reading from the map should be safe without blocking in that case...

Plus you're using a pointer for the map entry type, should I change it to a pointer as well?
Sorry for the dumb questions, I want to make the two implementations in sync while I am at it.

**Comment by zimmski** [comment]
- Reading from the map is not safe if it is possible to write the map at the same time. Therefore, the locking looks fine. Or did you mean something else?
- Every fixed-sized type that you can perform arithmetic operations on can overflow see https://en.wikipedia.org/wiki/Integer_overflow
- My problem with using a pure integer type instead of a pointer is, that the clang_visitChildren excepts a pointer.

**Pull request merged**
